### PR TITLE
Third Pages--Cleaning "People" and "More People"

### PR DESCRIPTION
**Pull request by alexhallenbeck**
Cleaned up misspelled "People" and "More People"

### CODE REVIEW

**Review by geealbers — APPROVED** [review]
Nice, thank you!

**Comment by geealbers** [comment]
Oh, one side note @alexhallenbeck. I realized your "Update objects.yaml" commit summaries are a little too generic once they're merged into the main branches. Could you use something like "Update maker names" or "Update sorting dates" going forward? It's more important to say what the update did then what file the update was made to. Thanks!

**Comment by alexhallenbeck** [comment]
@geealbers  Is this the commit summary I would fill in on my GitHub desktop? If it is, you're definitely right because I haven't been changing it all as I think "update objects.yaml" is the default. Will make sure this is more specific in the future.

**Comment by geealbers** [comment]
Yes, in GitHub Desktop, and yes, makes sense that "Update objects.yaml" was its default value. Thanks for changing them going forward

**Pull request merged**
