### PR TITLE
Scores adding "people" (objects thru 200)

### PR DESCRIPTION
**Pull request by alexhallenbeck**
Closed the old PR and re-opened in the same branch (because nothing was merged)...let me know if I am doing this correctly! 

So here is the next 100 with three I flagged for your review: 

-id 112: Cage is the only person discussed in the article so I added only him to "people" (along with press author already listed from automation). But MC Richards, Tudor, and Cunningham are briefly listed in extended caption. 

-id 165. Example of “Piano Pieces for David Tudor” being nested within a larger Bussotti composition. Is Tudor a “people” here, then? He seems a little bit removed from the object at hand. 

-id 195. These are Tudor's lecture notes where he briefly writes about being indebted to Feldman (which is stated in the extended caption)--should Feldman be included in "people"?

### CODE REVIEW

**Comment by geealbers** [comment]
@alexhallenbeck these are looking good.

For the pull request, you don't need to close and reopen new ones. You can just keep making commits to your branch as they'll be added here automatically. And you can add a comment occasionally when you want to draw my attention to a few examples. 

As to your most recent examples, here are my thoughts>

-id 112: I think you were right to leave out Richards, Tudor, and Cunningham. While they are mentioned in the caption, the People filters are really about the people connected to the object explicitly, and those three aren't in this case.

-id 165. I agree Tudor seems a little removed from this object, but I would still list him since we list him with other versions of Piano Pieces for David Tudor, and those sheets are here too. Also it's not obvious looking at the object, but a couple sheets of Piano Pieces that appear here actually have some pencil markings by Tudor that Mike explicitly calls out in his Commentary in the Bussotti chapter.

-id 195. Yes, I would include Feldman. The mention may be brief but he is connected to this object in some way. For example, I could imagine a Feldman scholar being interested that Tudor referenced him in this way.

**Comment by alexhallenbeck** [comment]
@geealbers another 100 done, but a bit trickier. Some of these that I'd like your feedback on when you get a second: 

-id 239: I put Wada and Kosugi as "people" and I put Sarah Cooper (as the curator) as "more people" 

-id 243: Just wanted confirmation that you agree with my sorting here. 

-id 251: host of people included in extended caption (but not the object title). The compositions was originally part of "An Anthology" but I didn't include the publishers of that (Mac Low, Young, etc) 

-id 260: Is it worth including the main Scores "people" listed on the second page of this document? 

-id 267, 271 and others around here: these objects have a ton of "people" and "more people" in print that will take me awhile to list out. Let me know if you think it's worth me doing this!

**Comment by geealbers** [comment]
-id 239: Can you ask Mike and Natilee whether they want Sarah listed as People or More People. And that should be applied to this whole series of videos for her and Tashi as curators. And you're right that Tashi should appear in People for those in which he also performed.

-id 243: Agree about Paston. Sarah and Tashi should be on the same level as with 239

-id 251: Yes, I think best not to include the three publishers of An Anthology at every mention of them. I would though definitely add all the listed performers to More People.

-id 260: I could go either way

-id 267, 271 I think it's worth listing out all these people, but maybe limit it to primary names you can see in skimming without reading every page. Such as the names at the tops of the cards in 267, or in that list on the first page of 271

**Comment by alexhallenbeck** [comment]
@geealbers whew, OK I've gone through all of them now. A couple representative ones to flag from this large final batch: 

id: 349–350: should I add Maciunas as "people"? (I think he helped design this but is not mentioned in the captions here) 
id 356: lots of options here, just focused on the pieces that were actually performed in the video (I think...?)
id 442: let me know if you agree with my classifications here
id 471: participants/performers as "people" or "more people"?
id: 574: let me know if you agree with this. 

The last thing, I think, is to send Natilee and Mike a list of people I've compiled and let them decide if they should be "people" or "more people" (if they are more tangentially related to the object in question; if they are in the title they are already added to "people") 
   -Nam June Paik
   -Christian Wolff
   -MC Richards
   -Walter De Maria
   -David Gordon
   -Dick Higgins

**Review by geealbers — APPROVED** [review]

**Pull request merged**
